### ISSUE TITLE
Support for partials

### ISSUE THREAD

**Issue by sethladd** [xxgreg/mustache#11]
We could really use this, if it's possible to do.

Thanks for the help!

**Comment by xxgreg** [comment]
Found a couple of hours to hack on this. 

An initial implementation is on this branch.
https://github.com/xxgreg/mustache/tree/partials

This allows the end user to provide a closure (a PartialResolver) that will return the correct template given a string name. This allows partials to be used in the browser, but also for a server side client to provide a resolver which looks up templates using dart:io to access the file system.

**Comment by sethladd** [comment]
wow, thanks!

**Comment by xxgreg** [comment]
On pub in version 0.2
