### ISSUE TITLE
0.2.0 release - feedback please!

### ISSUE THREAD

**Issue by xxgreg** [xxgreg/mustache#13]
I'd like to push a 0.2 release of the mustache package up within the next week or two.

The branch is here
https://github.com/xxgreg/mustache/tree/0.2

These are the changes I've made:
  
  * Implemented partials
  * Implemented lambdas
  * Tagged dart:mirrors import with MirrorsUsed so this library can be used with dart2js.
  Publish a mustache_io package which makes rendering templates stored in files easy. See:
  https://github.com/xxgreg/mustache_io
  * Will publish a separate mustache_no_mirrors package which provides the same api but with no mirrors support, this is for use in the browser. See: https://github.com/xxgreg/mustache/tree/no_mirrors

If you're using this package, I'd really appreciate if you could have a look and see if these changes work for you, or if you'd like things done differently.

Cheers!

**Comment by xxgreg** [comment]
Shout out if you have any opinions on these changes.

@dominique-locatelli
@timkendrick 
@sethladd 
@timkendrick 
@Thiltal
@yjbanov

**Comment by sethladd** [comment]
Have you considered putting the two packages (_io _no_mirrors) into the same package? It's probably less to manage, and easier for users to find. It's OK to ask a consumer of this package to import a specific library from your package (e.g. the http package does this)

**Comment by xxgreg** [comment]
Sorry I'll be more clear.

The mustache_io package depends on mustache, i.e. it isn't another implementation of mustache. I'm planning for it to contain utilities for loading templates from directories and files, along with caching and reloading. I don't want to combine it with mirrors because some people do want to use mirrors with dart2js, and dart2js and io don't mix.

mustache_no_mirrors is a copy of the mustache package with the mirrors code commented out. I originally refactored the code to make this pluggable, but this was a bit annoying for the common mirrors use case. So I went for the quick and ugly solution. I'm looking forward to seeing what happens with the "configurable imports" discussion at TC52. This will hopefully help me implement a better solution that shares code.

**Comment by xxgreg** [comment]
Pushed 0.2 to pub.
