### ISSUE TITLE
Support lambdas

### ISSUE THREAD

**Issue by michaelhixson** [xxgreg/mustache#4]
Hello.  It's me again. :)

I have an implementation of lambdas locally.  Are you interested in adding lambda support to this library?

If so, how can they be properly tested in mustache_spec_test?  The ~lambdas.yml file seems to include code for various languages as strings, which I take to mean it implicitly relies on the existence of an "eval" function in the language.  AFAIK Dart doesn't have eval, so...

Any advice on how to make the tests work?  My current thought is to:

* Add 'dart' entries under each 'lambda' section in ~lambdas.yml.
* In mustache_spec_test.dart, add something like this at the top of the runTest function:

```
// Special case: the lambda tests contain source code for various languages.
// Extract out this code and run it in a new isolate.  Then, replace that
// entry with a map with a function that talks to the isolate.
if (data.containsKey('lambda') && data['lambda'].containsKey['dart']) {
    String lambdaSource = data['lambda']['dart'];
    String lambdaUri = 'tmp/lambda.dart';
    File lambdaFile = new File('tmp/lambda.dart');
    IOSink lambdaSink = lambdaFile.openWrite();
    lambdaSink.add(lambdaSource.codeUnits);
    isolate.SendPort port = isolate.spawnUri(lambdaUri);
    data['lambda'] = ??? // I reached the limit of my Dart skills
}
```

**Comment by sethladd** [comment]
Friendly ping. Does this library support lambdas?

**Comment by xxgreg** [comment]
Lambdas are not yet supported.

I'll see if I can find time over the next week or two to come up with some solutions to the various issues.

I'm still not 100% sure how I want to exposed the API for lambda's and partials. I'll put something up in another branch. Feedback would be appreciated.

**Comment by xxgreg** [comment]
I've cooked up a simple implementation for lambdas. The following works - is this what you were expecting?

      var template = '<{{#markdown}}{{content}}{{/markdown}}>';
      var values = {'markdown': (s) => s.toLowerCase(), 'content': 'OI YOU!'};
      var output = '<oi you!>';
      expect(parse(template).renderString(values), equals(output));

Note this is actually not correct as per the mustache spec, which says:

    Lambdas
    When the value is a callable object, such as a function or lambda, the object will be invoked
    and passed the block of text. The text passed is the literal block, unrendered. {{tags}} will not
    have been expanded - the lambda should do that on its own. In this way you can implement
    filters or caching.

However many popular mustache libraries implement this differently, and I think generally the simpler behaviour, as I have currently implemented is better. I have ideas about how I could variable expansion later in a backwards compatible way.

The code is in the partials branch:
https://github.com/xxgreg/mustache/tree/partials

**Comment by sethladd** [comment]
FWIW I don't have a problem with managing the mustache conversion inside the lambda.

Otherwise, looks good!

**Comment by sethladd** [comment]
One benefit of your solution (and a problem with the "official" way mustache specs this behavior): lambdas inside of loops will get an implicitly relative context.

With the "official" way, there's no way to understand that your lambda is executing inside of a nested context. The current context isn't passed to the lambda.

**Comment by xxgreg** [comment]
I've implemented lambdas like this now - see below. Hopefully the best of both worlds. The String returned from the lambda isn't evaluated, but you can do that yourself in the lambda by calling renderSource(source).

    typedef Object LambdaFunction(LambdaContext context);

    /// Passed as an argument to a mustache lambda function.
    abstract class LambdaContext {
  
      /// Render the current section tag in the current context and return the
      /// result as a string.
      String renderString();
    
      /// Get the unevaluated template source for the current section tag.
      String get source;
  
      /// Evaluate the string as a mustache template using the current context.
      String renderSource(String source);  
  
     /// Lookup the value of a variable in the current context.
     Object lookup(String variableName);
    }

**Comment by xxgreg** [comment]
Now on pub version 0.2.
