### ISSUE TITLE
Bug that leads to unexplanatory error when bad formed template processed

### ISSUE THREAD

**Issue by Rodsevich** [xxgreg/mustache#42]
![image](https://user-images.githubusercontent.com/1907844/51918629-a6c2fb80-23c0-11e9-9b07-7b973568b069.png)
With just defining the var either to true or false the exception is thrown properly

**Comment by Rodsevich** [comment]
Created the PR #43

**Comment by xxgreg** [comment]
Thanks Nico. I've merged this and pushed version 1.1.1 to pub.
