### ISSUE TITLE
Dart2JS on import 'dart:mirrors' -- This import is not annotated with @MirrorsUsed

### ISSUE THREAD

**Issue by udhos** [xxgreg/mustache#7]
Is this known?

[Info from Dart2JS on config_template|web/config_template.dart]:
packages\mustache\mustache.dart:3:1:
This import is not annotated with @MirrorsUsed, which may lead to unnecessarily large generated code.
Try adding '@MirrorsUsed(...)' as described at https://goo.gl/Akrrog.
import 'dart:mirrors';
^^^^^^^^^^^^^^^^^^^^^^

**Comment by sethladd** [comment]
Friendly ping... just talked to a customer that was using mustache with dart2js and they had a very big file output size.

Until this library implements @MirrorsUsed or gets a code generator, can you add some pretty big and bold notes to the README that warns people about using this library with dart2js? I think it'll really help.

Thanks so much!

**Comment by xxgreg** [comment]
Thanks for the ping. I've merged your comment. I'm not really familiar with MirroredUsed and dart2js. I don't use mirrors with dart2js. 

As far as I can tell this library can't specify a list of reflective targets in a MirrorsUsed tag, as the targets belong to the client libraries.

Do you think publishing a version of this library which doesn't use mirrors - i.e. only maps - is a good solution?

**Comment by sethladd** [comment]
I believe there's a way to tell MirrorsUsed to reflect on classes that have a particular annotation. That might work for now.

For example:

```
@Mustache
class Data {
  String name;
}
```

and in your code:

```
@MirrorsUsed(metaTargets: [Mustache])
```

I think?

**Comment by xxgreg** [comment]
Keeping an eye on this...

https://github.com/dart-lang/reflectable

**Comment by xxgreg** [comment]
Just noticed that Dominique also has a patch which removes mirrors:

https://github.com/dominique-locatelli/mustache-no-mirror/commit/9573a87da5575b881f980de02d05d772c4ab5be4

**Comment by xxgreg** [comment]
Added MirrorsUsed. Tested that it reduces minified build size.

**Comment by sethladd** [comment]
woot!!!
